### PR TITLE
Update f6

### PR DESCRIPTION
**Pull request by lijinfeng2011**

### CODE REVIEW

**Comment by openc3-bot-001** [comment]
🚀Thanks for your contribution🎉. CodeBot(AI) will review your code first🔥

**Comment by lijinfeng2011** [comment]
w

**Review by openc3-bot-001 — APPROVED** [review]

**Comment by openc3-bot-001** [comment]
🚀Thanks for your contribution🎉. CodeBot(AI) will review your code first🔥

**Comment by openc3-bot-001** [comment]
🚀Thanks for your contribution🎉. CodeBot(AI) will review your code first🔥

**Pull request merged**
